/* Nomad AI — real place data.
   GENERATED by scripts/export-to-phone-app.ts in the nomad-ai project. Do not
   edit by hand: re-run "npm run export:app" instead.

   Two tables, kept separate on purpose:
     coords  — real coordinates for places data.js already defines, matched by
               name and applied by id, so photographs and the Kyrgyz/Russian
               translations keyed to those ids keep working.
     extras  — places only the Telegram bot's database carries, with ids from
               1001 so they can never collide with the design's own 1–37.

   "geo" records how each coordinate is known:
     bot        the bot's own exact coordinate
     nominatim  resolved by name on OpenStreetMap and distance-checked
     bot-approx district-level only — the app labels these as approximate
*/
window.NOMAD_PLACES = {
  generatedAt: "2026-08-13T11:12:05.396Z",
  coords: [
 {
  "_note": "Added by hand: the export had no coordinate for Jeti-Oguz Gorge, so it never appeared on the map and silently dropped out of the Issyk-Kul trip route. This is the Seven Bulls formation, the part visitors actually go to.",
  "id": 35,
  "lat": 42.3417,
  "lng": 78.2264,
  "geo": "nominatim"
 },
 {
  "id": 3,
  "lat": 42.6403,
  "lng": 74.4796,
  "geo": "bot-approx"
 },
 {
  "id": 9,
  "lat": 42.4832821,
  "lng": 78.4000716,
  "geo": "nominatim"
 },
 {
  "id": 8,
  "lat": 42.4620398,
  "lng": 77.0789862,
  "geo": "nominatim"
 },
 {
  "id": 27,
  "lat": 42.877,
  "lng": 74.586,
  "geo": "bot-approx"
 },
 {
  "id": 25,
  "lat": 42.8780457,
  "lng": 74.6127546,
  "geo": "nominatim"
 },
 {
  "id": 26,
  "lat": 42.876,
  "lng": 74.612,
  "geo": "bot-approx"
 },
 {
  "id": 37,
  "lat": 41.7585155,
  "lng": 75.126134,
  "geo": "nominatim"
 },
 {
  "id": 19,
  "lat": 42.8250717,
  "lng": 74.6028192,
  "geo": "nominatim"
 },
 {
  "id": 21,
  "lat": 42.830372,
  "lng": 74.588412,
  "geo": "bot"
 },
 {
  "id": 30,
  "lat": 42.8790496,
  "lng": 74.6179445,
  "geo": "nominatim"
 },
 {
  "id": 36,
  "lat": 42.4087398,
  "lng": 78.5784122,
  "geo": "nominatim"
 },
 {
  "id": 24,
  "lat": 42.874,
  "lng": 74.612,
  "geo": "bot-approx"
 },
 {
  "id": 16,
  "lat": 42.8686956,
  "lng": 74.6069283,
  "geo": "nominatim"
 },
 {
  "id": 34,
  "lat": 42.1566414,
  "lng": 77.3540202,
  "geo": "nominatim"
 },
 {
  "id": 7,
  "lat": 42.877,
  "lng": 74.6038,
  "geo": "bot-approx"
 },
 {
  "id": 2,
  "lat": 42.6295411,
  "lng": 74.6212756,
  "geo": "nominatim"
 },
 {
  "id": 28,
  "lat": 42.876,
  "lng": 74.611,
  "geo": "bot-approx"
 },
 {
  "id": 6,
  "lat": 42.876437,
  "lng": 74.603723,
  "geo": "bot"
 },
 {
  "id": 5,
  "lat": 42.873,
  "lng": 74.612,
  "geo": "bot-approx"
 },
 {
  "id": 31,
  "lat": 42.874,
  "lng": 74.6,
  "geo": "bot-approx"
 },
 {
  "id": 1,
  "lat": 42.8763118,
  "lng": 74.6167125,
  "geo": "nominatim"
 },
 {
  "id": 4,
  "lat": 42.8746,
  "lng": 74.5686,
  "geo": "bot"
 },
 {
  "id": 10,
  "lat": 42.7464284,
  "lng": 75.2500795,
  "geo": "nominatim"
 },
 {
  "id": 33,
  "lat": 42.6699123,
  "lng": 74.6419999,
  "geo": "nominatim"
 },
 {
  "id": 13,
  "lat": 42.8726355,
  "lng": 74.5897956,
  "geo": "nominatim"
 },
 {
  "id": 18,
  "lat": 42.878302,
  "lng": 74.606733,
  "geo": "bot"
 },
 {
  "id": 14,
  "lat": 42.8859944,
  "lng": 74.565128,
  "geo": "nominatim"
 },
 {
  "id": 12,
  "lat": 42.858422,
  "lng": 74.6000842,
  "geo": "nominatim"
 },
 {
  "id": 11,
  "lat": 42.85251,
  "lng": 74.60793,
  "geo": "bot"
 },
 {
  "id": 22,
  "lat": 42.856602,
  "lng": 74.590326,
  "geo": "bot"
 },
 {
  "id": 29,
  "lat": 42.9385645,
  "lng": 74.6204892,
  "geo": "nominatim"
 },
 {
  "id": 32,
  "lat": 42.8746,
  "lng": 74.5686,
  "geo": "bot"
 },
 {
  "id": 20,
  "lat": 42.8791971,
  "lng": 74.5998024,
  "geo": "nominatim"
 }
],
  extras: [
 {
  "id": 1001,
  "name": "Asia Mall",
  "cat": "Market",
  "rating": 4.9,
  "reviews": 0,
  "dist": "",
  "price": "Free entry",
  "hours": "10:00–22:00",
  "travel": "",
  "addr": "Проспект Чынгыза Айтматова, 3, Бишкек",
  "desc": "Large modern shopping and entertainment mall. Praised for cinema, food court and family activities.",
  "dishes": [],
  "listTitle": "Good to know",
  "review": "",
  "lat": 42.8557139,
  "lng": 74.5849844,
  "geo": "nominatim",
  "ph": "Asia Mall",
  "slot": ""
 },
 {
  "id": 1002,
  "name": "Dordoi Plaza",
  "cat": "Market",
  "rating": 4.9,
  "reviews": 0,
  "dist": "",
  "price": "Free entry",
  "hours": "10:00–20:00",
  "travel": "",
  "addr": "Улица Ибраимова, 115/2, Бишкек",
  "desc": "Popular shopping and trade center in the city. Praised for the range of shops and central location.",
  "dishes": [],
  "listTitle": "Good to know",
  "review": "",
  "lat": 42.8747544,
  "lng": 74.6187451,
  "geo": "nominatim",
  "ph": "Dordoi Plaza",
  "slot": ""
 },
 {
  "id": 1003,
  "name": "Museum of Fine Arts (Gapar Aitiev)",
  "cat": "Museum",
  "rating": 4.9,
  "reviews": 0,
  "dist": "",
  "price": "40 som ($0.5)",
  "hours": "10:00–16:00",
  "travel": "",
  "addr": "Yusup Abdrakhmanov St 196, Bishkek",
  "desc": "Main art museum — felt carpets (shyrdak), nomad art, jewelry. Praised for the traditional Kyrgyz applied-art collection.",
  "dishes": [],
  "listTitle": "Good to know",
  "review": "",
  "lat": 42.8786176,
  "lng": 74.6106862,
  "geo": "nominatim",
  "ph": "Museum of Fine Arts (Gapar Aitiev)",
  "slot": ""
 },
 {
  "id": 1004,
  "name": "Bellagio Premium",
  "cat": "Kyrgyz cuisine",
  "rating": 4.8,
  "reviews": 0,
  "dist": "",
  "price": "2500 som ($28)",
  "hours": "12:00–00:00",
  "travel": "",
  "addr": "БЦ Avangard, ул. Токтогула, 125/1, Бишкек (4 этаж)",
  "desc": "Upscale restaurant with city views. Praised for elegant dining and service.",
  "dishes": [
   "European & premium cuisine"
  ],
  "listTitle": "Good to know",
  "review": "",
  "lat": 42.87269,
  "lng": 74.597351,
  "geo": "bot",
  "ph": "Bellagio Premium",
  "slot": ""
 },
 {
  "id": 1005,
  "name": "Bishkek Circus",
  "cat": "Culture",
  "rating": 4.8,
  "reviews": 0,
  "dist": "",
  "price": "Tickets ~400 som ($4.5)",
  "hours": "Weekend shows",
  "travel": "",
  "addr": "Улица Жумабека, 119, Бишкек",
  "desc": "Soviet-era permanent circus (built 1976). Praised as nostalgic family entertainment.",
  "dishes": [],
  "listTitle": "Good to know",
  "review": "",
  "lat": 42.881382,
  "lng": 74.614156,
  "geo": "bot",
  "ph": "Bishkek Circus",
  "slot": ""
 },
 {
  "id": 1006,
  "name": "Bishkek Park Mall",
  "cat": "Market",
  "rating": 4.8,
  "reviews": 0,
  "dist": "",
  "price": "Free entry",
  "hours": "10:00–22:00",
  "travel": "",
  "addr": "Kiev St 148, Bishkek",
  "desc": "Modern mall with international stores, cinema, food court. Praised for brands, cinema, and A/C comfort.",
  "dishes": [],
  "listTitle": "Good to know",
  "review": "",
  "lat": 42.8744865,
  "lng": 74.5904076,
  "geo": "nominatim",
  "ph": "Bishkek Park Mall",
  "slot": ""
 },
 {
  "id": 1007,
  "name": "GUM Chynar",
  "cat": "Market",
  "rating": 4.8,
  "reviews": 0,
  "dist": "",
  "price": "Free entry",
  "hours": "10:00–20:00",
  "travel": "",
  "addr": "Проспект Чуй, 92, Бишкек",
  "desc": "Classic city-center shopping. Praised for central location.",
  "dishes": [],
  "listTitle": "Good to know",
  "review": "",
  "lat": 42.874763,
  "lng": 74.614411,
  "geo": "bot",
  "ph": "GUM Chynar",
  "slot": ""
 },
 {
  "id": 1008,
  "name": "Kuurdak №1",
  "cat": "Kyrgyz cuisine",
  "rating": 4.8,
  "reviews": 0,
  "dist": "",
  "price": "900 som ($10)",
  "hours": "11:00–23:00",
  "travel": "",
  "addr": "Проспект Дэн Сяопина, 103, Бишкек",
  "desc": "Known for one of the best kuurdaks in town. Praised for rich, flavorful kuurdak.",
  "dishes": [
   "Kuurdak",
   "fried potatoes",
   "meat dishes"
  ],
  "listTitle": "Good to know",
  "review": "",
  "lat": 42.876,
  "lng": 74.59,
  "geo": "bot-approx",
  "ph": "Kuurdak №1",
  "slot": ""
 },
 {
  "id": 1009,
  "name": "Bugu",
  "cat": "Kyrgyz cuisine",
  "rating": 4.7,
  "reviews": 0,
  "dist": "",
  "price": "1200 som ($14)",
  "hours": "11:00–00:00",
  "travel": "",
  "addr": "Улица Сухэ-Батора, 3, Бишкек",
  "desc": "Modern restaurant with Kyrgyz and European dishes. Praised for atmosphere, interior and food quality.",
  "dishes": [
   "Kyrgyz & European cuisine",
   "grills"
  ],
  "listTitle": "Good to know",
  "review": "",
  "lat": 42.824184,
  "lng": 74.61889,
  "geo": "bot",
  "ph": "Bugu",
  "slot": ""
 },
 {
  "id": 1010,
  "name": "Frunze",
  "cat": "Kyrgyz cuisine",
  "rating": 4.7,
  "reviews": 0,
  "dist": "",
  "price": "1500 som ($17)",
  "hours": "11:00–23:00",
  "travel": "",
  "addr": "Парк им. Ч. Айтматова, ул. Абдумомунова, 220а, Бишкек",
  "desc": "Refined Kyrgyz cuisine with a lovely summer terrace. Praised for beautiful presentation, atmosphere, professional service.",
  "dishes": [
   "Beshbarmak",
   "national dishes",
   "summer terrace"
  ],
  "listTitle": "Good to know",
  "review": "",
  "lat": 42.878886,
  "lng": 74.606941,
  "geo": "bot",
  "ph": "Frunze",
  "slot": ""
 },
 {
  "id": 1011,
  "name": "Furusato",
  "cat": "Kyrgyz cuisine",
  "rating": 4.7,
  "reviews": 0,
  "dist": "",
  "price": "1500 som ($17)",
  "hours": "12:00–23:00",
  "travel": "",
  "addr": "Улица Жоомарта Боконбаева, 132, Бишкек",
  "desc": "Japanese restaurant. Praised for sushi and authentic Japanese dishes.",
  "dishes": [
   "Japanese cuisine",
   "sushi",
   "rolls"
  ],
  "listTitle": "Good to know",
  "review": "",
  "lat": 42.8669748,
  "lng": 74.6012449,
  "geo": "nominatim",
  "ph": "Furusato",
  "slot": ""
 },
 {
  "id": 1012,
  "name": "Michelle Kitchen & Coffee",
  "cat": "Coffee",
  "rating": 4.7,
  "reviews": 0,
  "dist": "",
  "price": "1200 som ($14)",
  "hours": "24/7",
  "travel": "",
  "addr": "Аалы Токомбаева улица, 21/1, Бишкек",
  "desc": "Round-the-clock coffee and food. Praised for being open 24/7 with a real kitchen.",
  "dishes": [
   "Coffee",
   "full kitchen",
   "desserts"
  ],
  "listTitle": "Good to know",
  "review": "",
  "lat": 42.818186,
  "lng": 74.62158,
  "geo": "bot",
  "ph": "Michelle Kitchen & Coffee",
  "slot": ""
 },
 {
  "id": 1013,
  "name": "Pavlova",
  "cat": "Coffee",
  "rating": 4.7,
  "reviews": 0,
  "dist": "",
  "price": "1500 som ($17)",
  "hours": "09:00–23:00",
  "travel": "",
  "addr": "Baytik Tower, ул. Байтик баатыра, 66/1, Бишкек",
  "desc": "Elegant coffee and dessert spot. Praised for cakes and atmosphere.",
  "dishes": [
   "Coffee",
   "cakes",
   "desserts"
  ],
  "listTitle": "Good to know",
  "review": "",
  "lat": 42.854119,
  "lng": 74.609297,
  "geo": "bot",
  "ph": "Pavlova",
  "slot": ""
 },
 {
  "id": 1014,
  "name": "Skyberry",
  "cat": "Coffee",
  "rating": 4.7,
  "reviews": 0,
  "dist": "",
  "price": "1500 som ($17)",
  "hours": "08:00–23:00",
  "travel": "",
  "addr": "БЦ Avangard, ул. Токтогула, 125/1, Бишкек",
  "desc": "Stylish specialty coffee spot (2026 nominee). Praised for coffee quality and interior.",
  "dishes": [
   "Specialty coffee",
   "desserts"
  ],
  "listTitle": "Good to know",
  "review": "",
  "lat": 42.87269,
  "lng": 74.597351,
  "geo": "bot",
  "ph": "Skyberry",
  "slot": ""
 },
 {
  "id": 1015,
  "name": "Ata-Beyit Memorial",
  "cat": "Landmark",
  "rating": 4.6,
  "reviews": 0,
  "dist": "",
  "price": "Free",
  "hours": "09:00–18:00",
  "travel": "",
  "addr": "Мемориальный комплекс Ата-Бейит, с. Таш-Добо, Аламудунский р-н",
  "desc": "Solemn national memorial complex; resting place of Ch. Aitmatov. Praised as meaningful and reflective. Taxi ~30 km / 40 min from center (Chong-Tash); often part of a tour.",
  "dishes": [],
  "listTitle": "Good to know",
  "review": "",
  "lat": 42.71,
  "lng": 74.53,
  "geo": "bot-approx",
  "ph": "Ata-Beyit Memorial",
  "slot": ""
 },
 {
  "id": 1016,
  "name": "Manas Statue (Ala-Too)",
  "cat": "Landmark",
  "rating": 4.6,
  "reviews": 0,
  "dist": "",
  "price": "Free",
  "hours": "24/7",
  "travel": "",
  "addr": "Ala-Too Square, Bishkek",
  "desc": "Monument to the hero of the Manas epic on the main square. Praised as a top photo spot.",
  "dishes": [],
  "listTitle": "Good to know",
  "review": "",
  "lat": 42.8767,
  "lng": 74.6045,
  "geo": "bot-approx",
  "ph": "Manas Statue (Ala-Too)",
  "slot": ""
 },
 {
  "id": 1017,
  "name": "Rodem Coffee & Bakery",
  "cat": "Coffee",
  "rating": 4.6,
  "reviews": 0,
  "dist": "",
  "price": "1500 som ($17)",
  "hours": "08:00–22:00",
  "travel": "",
  "addr": "Улица Уметалиева, 109, Бишкек",
  "desc": "Coffee & bakery with a Korean kitchen. Praised for pastries, coffee and cozy space.",
  "dishes": [
   "Coffee",
   "bakery",
   "Korean kitchen"
  ],
  "listTitle": "Good to know",
  "review": "",
  "lat": 42.878697,
  "lng": 74.581808,
  "geo": "bot",
  "ph": "Rodem Coffee & Bakery",
  "slot": ""
 },
 {
  "id": 1018,
  "name": "Traveler's Coffee",
  "cat": "Coffee",
  "rating": 4.6,
  "reviews": 0,
  "dist": "",
  "price": "900 som ($10)",
  "hours": "08:00–00:00",
  "travel": "",
  "addr": "Улица Токтогула, 107, Бишкек",
  "desc": "Spacious cafe popular with students and remote workers. Praised for comfy space, WiFi, wide menu.",
  "dishes": [
   "Specialty coffee",
   "breakfast",
   "cakes"
  ],
  "listTitle": "Good to know",
  "review": "",
  "lat": 42.8725064,
  "lng": 74.6021321,
  "geo": "nominatim",
  "ph": "Traveler's Coffee",
  "slot": ""
 },
 {
  "id": 1019,
  "name": "Barashek",
  "cat": "Kyrgyz cuisine",
  "rating": 4.5,
  "reviews": 0,
  "dist": "",
  "price": "1000 som ($11)",
  "hours": "11:00–23:00",
  "travel": "",
  "addr": "Аалы Токомбаева улица, 78Б, Бишкек",
  "desc": "Authentic Kyrgyz cuisine with a focus on lamb. Praised for tender lamb dishes and welcoming ambiance.",
  "dishes": [
   "Lamb dishes",
   "Kyrgyz cuisine"
  ],
  "listTitle": "Good to know",
  "review": "",
  "lat": 42.82,
  "lng": 74.59,
  "geo": "bot-approx",
  "ph": "Barashek",
  "slot": ""
 },
 {
  "id": 1020,
  "name": "Bublik",
  "cat": "Coffee",
  "rating": 4.5,
  "reviews": 0,
  "dist": "",
  "price": "800 som ($9)",
  "hours": "08:00–22:00",
  "travel": "",
  "addr": "Сеть кофеен, филиалы:\n• Уметалиева 74\n• Боконбаева 103 (ЖК Триумф)\n• Тоголок Молдо 5/1\n• Токтогула 75/1\n• Тыналиева 3/14\n• Токтогула 234\n• 10-й мкр, 33\n• 7-й мкр, 33/3\n• Сухэ-Батора 21",
  "desc": "Cozy coffee & bakery chain with branches across the city. Praised for coffee, fresh bakery and interior.",
  "dishes": [
   "Coffee",
   "bakery",
   "desserts"
  ],
  "listTitle": "Good to know",
  "review": "",
  "lat": 42.8734751,
  "lng": 74.5960241,
  "geo": "nominatim",
  "ph": "Bublik",
  "slot": ""
 },
 {
  "id": 1021,
  "name": "Flag Square (Ala-Too)",
  "cat": "Park",
  "rating": 4.5,
  "reviews": 0,
  "dist": "",
  "price": "Free",
  "hours": "Guard change hourly 07:00–18:00",
  "travel": "",
  "addr": "Ala-Too Square, Bishkek",
  "desc": "State flagpole with an hourly changing-of-the-guard ceremony. Praised for the guard ceremony on the hour.",
  "dishes": [],
  "listTitle": "Good to know",
  "review": "",
  "lat": 42.876549,
  "lng": 74.603246,
  "geo": "bot",
  "ph": "Flag Square (Ala-Too)",
  "slot": ""
 },
 {
  "id": 1022,
  "name": "Mubarak",
  "cat": "Kyrgyz cuisine",
  "rating": 4.5,
  "reviews": 0,
  "dist": "",
  "price": "900 som ($10)",
  "hours": "10:00–23:00",
  "travel": "",
  "addr": "Сеть чайхан, филиалы:\n• БЦ Гоголь (Гоголя 28)\n• Чуй 104\n• М. Горького 148\n• Тыныстанова 94\n• Сухэ-Батора 5/3\n• Киевская 206\n• Тыналиева 116\n• Айтматова 299/7а",
  "desc": "Wildly popular, spotless, stylish spot in the center. Praised for cleanliness, fast service, consistent quality.",
  "dishes": [
   "Kyrgyz classics",
   "plov",
   "grills"
  ],
  "listTitle": "Good to know",
  "review": "",
  "lat": 42.8755612,
  "lng": 74.609625,
  "geo": "nominatim",
  "ph": "Mubarak",
  "slot": ""
 },
 {
  "id": 1023,
  "name": "Torro Grill & Bar",
  "cat": "Kyrgyz cuisine",
  "rating": 4.5,
  "reviews": 0,
  "dist": "",
  "price": "2800 som ($32)",
  "hours": "12:00–00:00",
  "travel": "",
  "addr": "Улица Шопокова, 93, Бишкек (Парк Театральный)",
  "desc": "Stylish steakhouse, date-night ready. Praised for juicy steaks, wine list, friendly service.",
  "dishes": [
   "T-bone",
   "Ribeye steaks",
   "wine"
  ],
  "listTitle": "Good to know",
  "review": "",
  "lat": 42.8786739,
  "lng": 74.6149059,
  "geo": "nominatim",
  "ph": "Torro Grill & Bar",
  "slot": ""
 },
 {
  "id": 1024,
  "name": "Zaandukki",
  "cat": "Kyrgyz cuisine",
  "rating": 4.4,
  "reviews": 0,
  "dist": "",
  "price": "1500 som ($17)",
  "hours": "11:00–23:00",
  "travel": "",
  "addr": "Улица Якова Логвиненко, 1в, Бишкек",
  "desc": "Georgian restaurant. Praised for khachapuri and khinkali.",
  "dishes": [
   "Georgian cuisine",
   "khinkali",
   "khachapuri"
  ],
  "listTitle": "Good to know",
  "review": "",
  "lat": 42.8642384,
  "lng": 74.5990338,
  "geo": "nominatim",
  "ph": "Zaandukki",
  "slot": ""
 },
 {
  "id": 1025,
  "name": "Espressolab",
  "cat": "Coffee",
  "rating": 4.3,
  "reviews": 0,
  "dist": "",
  "price": "800 som ($9)",
  "hours": "08:00–22:00",
  "travel": "",
  "addr": "Парк им. Ч. Айтматова, просп. Чуй, 187а, Бишкек",
  "desc": "Coffee chain spot by the park. Praised for quick service and location.",
  "dishes": [
   "Espresso drinks",
   "snacks"
  ],
  "listTitle": "Good to know",
  "review": "",
  "lat": 42.876647,
  "lng": 74.608528,
  "geo": "bot",
  "ph": "Espressolab",
  "slot": ""
 },
 {
  "id": 1026,
  "name": "Tubeteyka",
  "cat": "Kyrgyz cuisine",
  "rating": 4.3,
  "reviews": 0,
  "dist": "",
  "price": "700 som ($8)",
  "hours": "10:00–23:00",
  "travel": "",
  "addr": "Парк им. И.В. Панфилова, Бишкек",
  "desc": "Casual Central-Asian eatery, lively vibe. Praised for friendly service and comfort food.",
  "dishes": [
   "Central-Asian mix",
   "plov",
   "manti"
  ],
  "listTitle": "Good to know",
  "review": "",
  "lat": 42.876,
  "lng": 74.595,
  "geo": "bot-approx",
  "ph": "Tubeteyka",
  "slot": ""
 },
 {
  "id": 1027,
  "name": "Dordoi Bazaar Food Court",
  "cat": "Street food",
  "rating": 4.2,
  "reviews": 0,
  "dist": "",
  "price": "250 som ($3)",
  "hours": "08:00–18:00",
  "travel": "",
  "addr": "Дордой (ул. Рынок Дордой), Бишкек",
  "desc": "Eat cheap while exploring one of Asia's largest markets. Praised for variety and rock-bottom prices.",
  "dishes": [
   "Central-Asian fast food",
   "noodles",
   "plov"
  ],
  "listTitle": "Good to know",
  "review": "",
  "lat": 42.926,
  "lng": 74.656,
  "geo": "bot-approx",
  "ph": "Dordoi Bazaar Food Court",
  "slot": ""
 },
 {
  "id": 1030,
  "name": "Lagman House",
  "cat": "Street food",
  "rating": 4.1,
  "reviews": 0,
  "dist": "",
  "price": "220 som ($2.5)",
  "hours": "10:00–21:00",
  "travel": "",
  "addr": "Moskovskaya 30, Bishkek",
  "desc": "Big bowls of hand-pulled lagman. Praised for filling noodles at low cost.",
  "dishes": [
   "Lagman",
   "Soup",
   "Tea"
  ],
  "listTitle": "Good to know",
  "review": "",
  "lat": 42.879,
  "lng": 74.6,
  "geo": "bot-approx",
  "ph": "Lagman House",
  "slot": ""
 },
 {
  "id": 1031,
  "name": "Moqa",
  "cat": "Coffee",
  "rating": 4.1,
  "reviews": 0,
  "dist": "",
  "price": "1500 som ($17)",
  "hours": "08:00–23:00",
  "travel": "",
  "addr": "Аалы Токомбаева улица, 25, Бишкек",
  "desc": "Coffee shop in the south of the city. Praised for coffee and interior.",
  "dishes": [
   "Coffee",
   "desserts"
  ],
  "listTitle": "Good to know",
  "review": "",
  "lat": 42.818,
  "lng": 74.621,
  "geo": "bot-approx",
  "ph": "Moqa",
  "slot": ""
 }
]
};
